FROM node:22-alpine

WORKDIR /managing-system

COPY package*.json ./
RUN apk add --no-cache docker-cli python3 make g++ \
  && npm ci

COPY tsconfig.json tsconfig.build.json ./
COPY prisma.config.ts ./
COPY prisma ./prisma
COPY src ./src

ENV DATABASE_URL=postgresql://postgres:postgres@managing-system-postgres:5432/managing_system

RUN npm run build

CMD ["npm", "run", "start:container"]
