FROM node:22-alpine

WORKDIR /managed-system

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
COPY tsconfig.json tsconfig.build.json prisma.config.ts ./
COPY src ./src

ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/managed_system

RUN npm run prisma:generate
RUN npm run build

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push && npm run start"]