FROM node:22-alpine

WORKDIR /managing-system

COPY package*.json ./
RUN npm install
RUN apk add --no-cache docker-cli

COPY tsconfig.json tsconfig.build.json ./
COPY src ./src

RUN npm run build

CMD ["npm", "run", "start"]
